/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelBarbeiroRouteImport } from './routes/painel.$barbeiro'
import { Route as ApiPublicHooksLembretesRouteImport } from './routes/api/public/hooks/lembretes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelBarbeiroRoute = PainelBarbeiroRouteImport.update({
  id: '/painel/$barbeiro',
  path: '/painel/$barbeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksLembretesRoute = ApiPublicHooksLembretesRouteImport.update({
  id: '/api/public/hooks/lembretes',
  path: '/api/public/hooks/lembretes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/painel/$barbeiro': typeof PainelBarbeiroRoute
  '/painel/': typeof PainelIndexRoute
  '/api/public/hooks/lembretes': typeof ApiPublicHooksLembretesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/painel/$barbeiro': typeof PainelBarbeiroRoute
  '/painel': typeof PainelIndexRoute
  '/api/public/hooks/lembretes': typeof ApiPublicHooksLembretesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/painel/$barbeiro': typeof PainelBarbeiroRoute
  '/painel/': typeof PainelIndexRoute
  '/api/public/hooks/lembretes': typeof ApiPublicHooksLembretesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/painel/$barbeiro'
    | '/painel/'
    | '/api/public/hooks/lembretes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/painel/$barbeiro'
    | '/painel'
    | '/api/public/hooks/lembretes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/painel/$barbeiro'
    | '/painel/'
    | '/api/public/hooks/lembretes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PainelBarbeiroRoute: typeof PainelBarbeiroRoute
  PainelIndexRoute: typeof PainelIndexRoute
  ApiPublicHooksLembretesRoute: typeof ApiPublicHooksLembretesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/$barbeiro': {
      id: '/painel/$barbeiro'
      path: '/painel/$barbeiro'
      fullPath: '/painel/$barbeiro'
      preLoaderRoute: typeof PainelBarbeiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/lembretes': {
      id: '/api/public/hooks/lembretes'
      path: '/api/public/hooks/lembretes'
      fullPath: '/api/public/hooks/lembretes'
      preLoaderRoute: typeof ApiPublicHooksLembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PainelBarbeiroRoute: PainelBarbeiroRoute,
  PainelIndexRoute: PainelIndexRoute,
  ApiPublicHooksLembretesRoute: ApiPublicHooksLembretesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
