/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FabricioAdminRouteImport } from './routes/fabricio-admin'
import { Route as VictorAdminRouteImport } from './routes/victor-admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBarbeiroRouteImport } from './routes/admin.$barbeiro'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelBarbeiroRouteImport } from './routes/painel.$barbeiro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricioAdminRoute = FabricioAdminRouteImport.update({
  id: '/fabricio-admin',
  path: '/fabricio-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const VictorAdminRoute = VictorAdminRouteImport.update({
  id: '/victor-admin',
  path: '/victor-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBarbeiroRoute = AdminBarbeiroRouteImport.update({
  id: '/$barbeiro',
  path: '/$barbeiro',
  getParentRoute: () => AdminRoute,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelBarbeiroRoute = PainelBarbeiroRouteImport.update({
  id: '/painel/$barbeiro',
  path: '/painel/$barbeiro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/fabricio-admin': typeof FabricioAdminRoute
  '/victor-admin': typeof VictorAdminRoute
  '/admin/$barbeiro': typeof AdminBarbeiroRoute
  '/painel/$barbeiro': typeof PainelBarbeiroRoute
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fabricio-admin': typeof FabricioAdminRoute
  '/victor-admin': typeof VictorAdminRoute
  '/admin/$barbeiro': typeof AdminBarbeiroRoute
  '/painel/$barbeiro': typeof PainelBarbeiroRoute
  '/admin': typeof AdminIndexRoute
  '/painel': typeof PainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/fabricio-admin': typeof FabricioAdminRoute
  '/victor-admin': typeof VictorAdminRoute
  '/admin/$barbeiro': typeof AdminBarbeiroRoute
  '/painel/$barbeiro': typeof PainelBarbeiroRoute
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/fabricio-admin'
    | '/victor-admin'
    | '/admin/$barbeiro'
    | '/painel/$barbeiro'
    | '/admin/'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fabricio-admin'
    | '/victor-admin'
    | '/admin/$barbeiro'
    | '/painel/$barbeiro'
    | '/admin'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/fabricio-admin'
    | '/victor-admin'
    | '/admin/$barbeiro'
    | '/painel/$barbeiro'
    | '/admin/'
    | '/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FabricioAdminRoute: typeof FabricioAdminRoute
  VictorAdminRoute: typeof VictorAdminRoute
  PainelBarbeiroRoute: typeof PainelBarbeiroRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabricio-admin': {
      id: '/fabricio-admin'
      path: '/fabricio-admin'
      fullPath: '/fabricio-admin'
      preLoaderRoute: typeof FabricioAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/victor-admin': {
      id: '/victor-admin'
      path: '/victor-admin'
      fullPath: '/victor-admin'
      preLoaderRoute: typeof VictorAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$barbeiro': {
      id: '/admin/$barbeiro'
      path: '/$barbeiro'
      fullPath: '/admin/$barbeiro'
      preLoaderRoute: typeof AdminBarbeiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/painel/': {
      id: '/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/$barbeiro': {
      id: '/painel/$barbeiro'
      path: '/painel/$barbeiro'
      fullPath: '/painel/$barbeiro'
      preLoaderRoute: typeof PainelBarbeiroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBarbeiroRoute: typeof AdminBarbeiroRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBarbeiroRoute: AdminBarbeiroRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FabricioAdminRoute: FabricioAdminRoute,
  VictorAdminRoute: VictorAdminRoute,
  PainelBarbeiroRoute: PainelBarbeiroRoute,
  PainelIndexRoute: PainelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
